# Generated by Django 2.1.7 on 2019-03-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syozoku',
            name='home',
            field=models.CharField(default=999, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syozoku',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
