# Generated by Django 2.1.7 on 2019-03-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0002_auto_20190323_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year_of_birth',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
