# Generated by Django 2.1.7 on 2019-03-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0003_member_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
    ]
